CREATE DATABASE STUDENTAPI;

USE STUDENTAPI;

CREATE TABLE STUDENT(ID INT PRIMARY KEY NOT NULL, NAME VARCHAR(30), EMAIL VARCHAR(30), PHONE VARCHAR(10), ROLL INTEGER, GRADE VARCHAR(10), SCHOOL VARCHAR(30));

INSERT INTO `student` VALUES (1,'Mridul Tilwaliya','mridultilwaliya@gmail.com','9131857705',1,'A','KVB'),(2,'Rahul Kumar','rahulkumar@gmail.com','9074787559',2,'A','KVB'),(3,'Akash Jadhav','aakash@gmail.com','9131857455',3,'A','KVB');

SELECT * FROM STUDENT;